gpu:
  tags:
    - cobra
  script:
    - module purge
    - module load cmake/3.18 doxygen git
    - module load gcc/10 cuda/11.2
    - git --version
    - cmake --version
    - cmake -S . -B mrmd-build -DCMAKE_BUILD_TYPE=Debug -DCabana_ENABLE_CAJITA=OFF -DMRMD_WERROR=ON
    - cmake --build mrmd-build --target all -j 32
    - cd mrmd-build
    - srun --nodes=1 --ntasks=1 --cpus-per-task=1 --partition=gpudev --gres=gpu:v100:1 --constraint="gpu" --time=15:00 ctest --rerun-failed --output-on-failure -j 2
  variables:
    CMAKE_PREFIX_PATH: "~/software/kokkos-install"
    OMP_PROC_BIND: "spread"
    OMP_PLACES: "threads"
    CXX: "g++"
    CC: "gcc"