name: VALIDATE

on:
  push:

jobs:
  debug-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang' ]
        BACKEND: [ 'Kokkos_ENABLE_SERIAL', 'Kokkos_ENABLE_OPENMP' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - name: versions
        run: |
          cat /etc/os-release
          echo $PATH
          git --version
          cmake --version
          $CC --version
          $CXX --version

      - uses: actions/checkout@v4
        with:
          path: 'mrmd'

      - name: Configure
        run: |
          cmake \
            -S mrmd \
            -B mrmd-build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DMRMD_VERBOSE_ASSERTS=ON \
            -DMRMD_WERROR=ON \
            -DKokkos_ENABLE_DEBUG=ON \
            -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
            -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -D${{ matrix.BACKEND }}=ON

      - name: build dependencies
        run: cmake --build mrmd-build --target fmt gmock gmock_main gtest gtest_main Kokkos yaml-cpp yaml-cpp-parse yaml-cpp-read yaml-cpp-sandbox --parallel 2

      - name: build
        run: cmake --build mrmd-build --target all --parallel 2

      - name: Test
        working-directory: mrmd-build
        run: ctest --output-on-failure --parallel 2

  release-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang' ]
        BACKEND: [ 'Kokkos_ENABLE_SERIAL', 'Kokkos_ENABLE_OPENMP' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - name: versions
        run: |
          cat /etc/os-release
          echo $PATH
          git --version
          cmake --version
          $CC --version
          $CXX --version

      - uses: actions/checkout@v4
        with:
          path: 'mrmd'

      - name: Configure
        run: |
          cmake \ 
            -S mrmd \
            -B mrmd-build \
            -DCMAKE_BUILD_TYPE=Release \
            -DMRMD_VERBOSE_ASSERTS=ON \
            -DMRMD_WERROR=ON \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -D${{ matrix.BACKEND }}=ON

      - name: build dependencies
        run: cmake --build mrmd-build --target fmt gmock gmock_main gtest gtest_main Kokkos yaml-cpp yaml-cpp-parse yaml-cpp-read yaml-cpp-sandbox --parallel 2

      - name: build
        run: cmake --build mrmd-build --target all --parallel 2

      - name: Test
        working-directory: mrmd-build
        run: ctest --output-on-failure --parallel 2

  clang-format:
    runs-on: ubuntu-latest
    container: xzzx/devel:clang
    steps:
      - uses: actions/checkout@v4

      - name: run formatter
        run: |
          git config --global --add safe.directory /__w/mrmd/mrmd
          ./format.sh

      - name: check formatting
        run: git diff --exit-code
