name: VALIDATE

on:
  push:

jobs:
  debug-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang', 'icx', 'icc' ]
        BACKEND: [ 'Kokkos_ENABLE_SERIAL', 'Kokkos_ENABLE_OPENMP' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - name: versions
        run: |
          cat /etc/os-release
          echo $PATH
          git --version
          cmake --version
          $CC --version
          $CXX --version

      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          ref: 'master'
          path: 'kokkos'

      - name: kokkos
        run: |
          ls
          mkdir kokkos-build
          cmake \
            -S kokkos \
            -B kokkos-build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DKokkos_CXX_STANDARD=17 \
            -DKokkos_ENABLE_DEBUG=ON \
            -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
            -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -D${{ matrix.BACKEND }}=ON
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          path: 'mrmd'

      - name: Configure
        run: cmake -S mrmd -B mrmd-build -DCMAKE_BUILD_TYPE=Debug -DMRMD_VERBOSE_ASSERTS=ON

      - name: build dependencies
        run: cmake --build mrmd-build --target fmt gmock gmock_main gtest gtest_main yaml-cpp yaml-cpp-parse yaml-cpp-read yaml-cpp-sandbox -j 2

      - name: build
        run: cmake --build mrmd-build --target all -j 2

      - name: Test
        working-directory: mrmd-build
        run: ctest --output-on-failure -j 2

  release-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang', 'icx', 'icc' ]
        BACKEND: [ 'Kokkos_ENABLE_SERIAL', 'Kokkos_ENABLE_OPENMP' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - name: versions
        run: |
          cat /etc/os-release
          echo $PATH
          git --version
          cmake --version
          $CC --version
          $CXX --version

      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          ref: 'master'
          path: 'kokkos'

      - name: kokkos
        run: |
          ls
          mkdir kokkos-build
          cmake \
            -S kokkos \
            -B kokkos-build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_CXX_STANDARD=17 \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -D${{ matrix.BACKEND }}=ON
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          path: 'mrmd'

      - name: Configure
        run: cmake -S mrmd -B mrmd-build -DCMAKE_BUILD_TYPE=Release -DMRMD_VERBOSE_ASSERTS=ON

      - name: build dependencies
        run: cmake --build mrmd-build --target fmt gmock gmock_main gtest gtest_main yaml-cpp yaml-cpp-parse yaml-cpp-read yaml-cpp-sandbox -j 2

      - name: build
        run: cmake --build mrmd-build --target all -j 2

      - name: Test
        working-directory: mrmd-build
        run: ctest --output-on-failure -j 2

  benchmark:
    runs-on: ubuntu-latest
    container: xzzx/devel:clang
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake \
            -S kokkos \
            -B kokkos-build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_CXX_STANDARD=17 \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -DKokkos_ENABLE_OPENMP=ON
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos-tools'
          path: 'kokkos-tools'

      - name: make kokkos-tools memory-events
        working-directory: kokkos-tools/profiling/memory-events
        run: make

      - name: make kokkos-tools simple-kernel-timer-json
        working-directory: kokkos-tools/profiling/simple-kernel-timer-json
        run: make

      - uses: actions/checkout@v2
        with:
          path: 'mrmd'

      - name: Configure
        run: cmake -S mrmd -B mrmd-build -DCMAKE_BUILD_TYPE=Release -DMRMD_VERBOSE_ASSERTS=ON

      - name: Build
        run: cmake --build mrmd-build --target all -j 2

      - name: run performance benchmark
        working-directory: mrmd-build/examples/LennardJones
        env:
          KOKKOS_PROFILE_LIBRARY: /__w/mrmd/mrmd/kokkos-tools/profiling/simple-kernel-timer-json/kp_kernel_timer.so
          OMP_NUM_THREADS: 2
        run: ./LennardJones

      - name: run memory benchmark
        working-directory: mrmd-build/examples/LennardJones
        env:
          KOKKOS_PROFILE_LIBRARY: /__w/mrmd/mrmd/kokkos-tools/profiling/memory-events/kp_memory_events.so
          OMP_NUM_THREADS: 2
        run: ./LennardJones

      - uses: actions/upload-artifact@v2
        with:
          name: performance-data
          path: |
            mrmd-build/examples/LennardJones/*.json
            mrmd-build/examples/LennardJones/*.memspace_usage
            mrmd-build/examples/LennardJones/*.mem_events

  clang-format:
    runs-on: ubuntu-latest
    container: xzzx/devel:clang
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          ref: 'master'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake -S kokkos -B kokkos-build -DCMAKE_BUILD_TYPE=Debug -DKokkos_CXX_STANDARD=17
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2

      - name: run formatter
        run: ./format.sh

      - name: check formatting
        run: git diff --exit-code

  clang-tidy:
    runs-on: ubuntu-latest
    container: xzzx/devel:clang
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          ref: 'master'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake -S kokkos -B kokkos-build -DCMAKE_BUILD_TYPE=Debug -DKokkos_CXX_STANDARD=17
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          path: 'mrmd'

      - name: Configure
        run: cmake -S mrmd -B mrmd-build -DCMAKE_BUILD_TYPE=Debug -DMRMD_CLANG_TIDY=ON -DMRMD_VERBOSE_ASSERTS=ON

      - name: build dependencies
        run: cmake --build mrmd-build --target fmt gmock gmock_main gtest gtest_main yaml-cpp yaml-cpp-parse yaml-cpp-read yaml-cpp-sandbox -j 2

      - name: build
        run: cmake --build mrmd-build --target all -j 2
