name: VALIDATE

on:
  push:

jobs:
  debug-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang', 'icx', 'icc' ]
        BACKEND: [ 'Kokkos_ENABLE_SERIAL', 'Kokkos_ENABLE_OPENMP' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake \
            -S kokkos \
            -B kokkos-build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DKokkos_ENABLE_DEBUG=ON \
            -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
            -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -D${{ matrix.BACKEND }}=ON
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          path: 'ecab'

      - name: Configure
        run: cmake -S ecab -B ecab-build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build ecab-build --target all -j 2

      - name: Test
        working-directory: ecab-build
        run: ctest --rerun-failed --output-on-failure -j 2

  release-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang', 'icx', 'icc' ]
        BACKEND: [ 'Kokkos_ENABLE_SERIAL', 'Kokkos_ENABLE_OPENMP' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake \
            -S kokkos \
            -B kokkos-build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -D${{ matrix.BACKEND }}=ON
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          path: 'ecab'

      - name: Configure
        run: cmake -S ecab -B ecab-build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ecab-build --target all -j 2

      - name: Test
        working-directory: ecab-build
        run: ctest --rerun-failed --output-on-failure -j 2

  benchmark:
    runs-on: ubuntu-latest
    container: xzzx/devel:clang
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake \
            -S kokkos \
            -B kokkos-build \
            -DCMAKE_BUILD_TYPE=Release \
            -DKokkos_ENABLE_HWLOC=ON \
            -DKokkos_ENABLE_SERIAL=ON \
            -DKokkos_ENABLE_OPENMP=ON
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos-tools'
          path: 'kokkos-tools'

      - name: make kokkos-tools memory-events
        working-directory: kokkos-tools/profiling/memory-events
        run: |
          pwd
          make
          ls

      - name: make kokkos-tools simple-kernel-timer-json
        working-directory: kokkos-tools/profiling/simple-kernel-timer-json
        run: |
          pwd
          make
          ls

      - uses: actions/checkout@v2
        with:
          path: 'ecab'

      - name: Configure
        run: cmake -S ecab -B ecab-build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ecab-build --target all -j 2

      - name: run performance benchmark
        working-directory: ecab-build/examples/LennardJones
        env:
          KOKKOS_PROFILE_LIBRARY: /__w/ecab/ecab/kokkos-tools/profiling/simple-kernel-timer-json/kp_kernel_timer_json.so
          OMP_NUM_THREADS: 2
        run: |
          pwd
          ls /__w/ecab/ecab/kokkos-tools/
          ls /__w/ecab/ecab/kokkos-tools/profiling/
          ls /__w/ecab/ecab/kokkos-tools/profiling/simple-kernel-timer-json
          ./LennardJones
          ls

      - name: run memory benchmark
        working-directory: ecab-build/examples/LennardJones
        env:
          KOKKOS_PROFILE_LIBRARY: /__w/ecab/ecab/kokkos-tools/profiling/memory-events/kp_memory_events.so
          OMP_NUM_THREADS: 2
        run: ./LennardJones

      - uses: actions/upload-artifact@v2
        with:
          name: performance-data
          path: |
            ecab-build/examples/LennardJones/*.json
            ecab-build/examples/LennardJones/*.memspace_usage
            ecab-build/examples/LennardJones/*.mem_events

  clang-format:
    runs-on: ubuntu-latest
    container: xzzx/devel:clang
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kokkos/kokkos'
          path: 'kokkos'

      - name: kokkos
        run: |
          cmake -S kokkos -B kokkos-build -DCMAKE_BUILD_TYPE=Debug
          cmake --build kokkos-build --target all -j 2
          sudo cmake --install kokkos-build

      - uses: actions/checkout@v2

      - name: run formatter
        run: ./format.sh

      - name: check formatting
        run: git diff --exit-code
